/// PRECIOS Y PUNTAJES POR DEFECTO.

PUNTAJE[HUIRO,JOVEN] = 5;
PUNTAJE[HUIRO,ADULTO] = 10;
PUNTAJE[CONGRIO,JOVEN] = -50;
PUNTAJE[CONGRIO,ADULTO] = 100;
PUNTAJE[JERGUILLA,JOVEN] = -10;
PUNTAJE[JERGUILLA,ADULTO] = 25;
PUNTAJE[LOCO,JOVEN] = -25;
PUNTAJE[LOCO,ADULTO] = 50;
PUNTAJE[CARACOL,JOVEN] = 0;
PUNTAJE[CARACOL,ADULTO] = 0;
PUNTAJE[JAIBA,JOVEN] = -10;
PUNTAJE[JAIBA,ADULTO] = 30;

PRECIO[HUIRO,JOVEN] = 100;
PRECIO[HUIRO,ADULTO] = 200;
PRECIO[CONGRIO,JOVEN] = 500;
PRECIO[CONGRIO,ADULTO] = 1000;
PRECIO[JERGUILLA,JOVEN] = 200;
PRECIO[JERGUILLA,ADULTO] = 400;
PRECIO[LOCO,JOVEN] = 300;
PRECIO[LOCO,ADULTO] = 600;
PRECIO[CARACOL,JOVEN] = 0;
PRECIO[CARACOL,ADULTO] = 0;
PRECIO[JAIBA,JOVEN] = 100;
PRECIO[JAIBA,ADULTO] = 250;
